### PR TITLE
mention Croissant exporter in README

### PR DESCRIPTION
**Pull request by pdurbin**
In the end, this pull request is only updating the README to mention the new Croissant exporter at https://github.com/gdcc/exporter-croissant

See also these related issues and PRs:

- https://github.com/IQSS/dataverse/issues/10341
- https://github.com/IQSS/dataverse/pull/10533

### CODE REVIEW

**Comment by poikilotherm** [comment]
Two general things...

A) Should we create a parent POM here to make setup of exporters easier?
B) Do we want to publish these exporters to Maven Central?

**Comment by pdurbin** [comment]
I'm not opposed to a parent pom but I'm not sure I understand the benefits.

On a related note, I wanted tests in my exporters so I added JUnit here:

- #3

Yes, I think at least some of these exporters should be published to Maven Central.

The Croissant exporter, for example, we might want to ship with Dataverse. So I imagine we'd publish the jar to Maven Central and then add it to Dataverse either at build time or drop it into place (by default) with a script? I haven't thought this through completely.

**Comment by pdurbin** [comment]
I updated the title and description to say that this PR now simply updates the README to point to the new dedicated git repo: https://github.com/gdcc/exporter-croissant

**Comment by poikilotherm** [comment]
@pdurbin can we close this? The mention is already in. :smile:

**Comment by pdurbin** [comment]
@poikilotherm yes, the mention looks fine. Thanks for bringing this to my attention. Closing.

**Comment by pdurbin** [comment]
@poikilotherm I created this issue:

- #40

**Pull request closed without merging**
