### PR TITLE
Customizable RO-Crate metadata exporter

### PR DESCRIPTION
**Pull request by okaradeniz**
An RO-Crate metadata exporter that can be customized by editing a CSV file containing mappings between dataset metadata and RO-Crate entities. The hierarchy of data entities is also generated from the file/directory structure of the dataset and included in the export. 

The exporter uses JsonPath strings generated from the mappings contained in the CSV to convert the dataset JSON (from the ExportDataProvider) to ro-crate-metadata.json.

Customizability lets Dataverse installations tailor the metadata export to their own requirements and custom metadata blocks. The CSV can be edited by installations using a spreadsheet application to change the mappings. 

Known issues:  A bug resulting in some exports not working due to a faulty casting (WIP). Refactoring the code, populating the CSV, and better documentation are also WIP.

### CODE REVIEW

**Comment by pdurbin** [comment]
@okaradeniz thanks for the pull request. I've been arguing internally that it probably makes more sense for each external exporter to have its own GitHub repo and its own GitHub Actions that publish the jar file on Maven Central, as I've done at https://github.com/gdcc/exporter-croissant

What do you think? I'm happy to create a repo under gdcc for you if you like, and help you sent up the publishing to Maven Central.

**Comment by pdurbin** [comment]
@okaradeniz great, can you please go to https://github.com/gdcc to accept the invitation?

I just made you an admin on https://github.com/gdcc/exporter-ro-crate

What about @beepsoft and his pull request below?

- https://github.com/IQSS/dataverse/issues/8688

Would the two of you want to collaborate on a single RO-Crate exporter?

We can also take this to Zulip, of course: https://dataverse.zulipchat.com/#narrow/stream/379673-dev/topic/RO-Crate/near/400987511

**Comment by poikilotherm** [comment]
@okaradeniz @beepsoft please note that with #16 we will provide a common Parent POM for exporter plugins to simplify setup and releasing. Happy to receive feedback!

**Comment by poikilotherm** [comment]
Heads up that there is a milestone release of the parent POM now, so you can actually try stuff.

The example shows how to use the parent POM for now, see https://github.com/gdcc/dataverse-exporters/blob/main/example/pom.xml

Note the emptiness of that POM - in case you don't need much stuff, you might be just fine with this. It already take care about the most basic dependencies as well as build config.

**Comment by ErykKul** [comment]
@okaradeniz 

There is already a mention for this exporter in the readme and it has its own gddc repo. Can this PR be closed? Thanks!

Eryk

**Pull request closed without merging**
